### ISSUE TITLE
REQUEST: Being able to order this fully assembled would be great!

### ISSUE THREAD

**Issue by Misterke** [lucadentella/esp32s2Stick#2]
Ordering the PCB, still leaves sourcing all components and then having to mount them.  I would love a couple of devices like this, but don't have the components, nor the tools or skills for SMD mounting.  So, having a design that could be ordered with all the SMD parts already soldered on and other components added to the package as offered by a.o. JLC PCB, could really help.  Or perhaps a Chinese partner producing an end-user product giving you a cut?

**Comment by lucadentella** [comment]
Hi! Thanks for your comment... In the past I worked with some PCBA services but the minimum quantity was 20-30 pcs and honestly at the moment I don't have requests for pre-assembled boards (excluding your one ;) )

I checked with JLCPCB but they don't provide a "market", where I may upload design files, BoM... and let other users order my products. I may upload all the files required to order the boards directly using JLCPCB PCBA service, but be prepared because at least two components (the esp module and the usb connector) are "extended parts" and they require an extra fee to include them in your order... If you like, I may work on this tomorrow

**Comment by tqpgun** [comment]
any update on the BoM? i would love to get the exact components to order the pcb myself.

**Comment by lucadentella** [comment]
Hi, you can simply generate the BoM from Eagle using the included ULP: this way you're sure it's always updated with the design files.
